In [1]:
import numpy as np 

In [2]:
ar = np.array([[10,15 , 17,26,13,19] , [12,11,21,24,14,23] ]) 


In [3]:
ar.ravel() 


array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [4]:
ar.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [5]:
ar.resize(2,6)

In [6]:
ar

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [7]:
np.hsplit(ar , 2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [8]:
np_lins =np.linspace(1,6,5) 
print(np_lins)

[1.   2.25 3.5  4.75 6.  ]


In [9]:
import pandas as pd 

In [10]:
df = pd.DataFrame({"London": {2012:205} , "America": {2008: 204}}) 

In [11]:
df

London  America
2012   205.0      NaN
2008     NaN    204.0

% matplotlib inline that to display the plot in jupyter notebook 
plt.legend to display the plot based on the some condition 